### PR TITLE
slight change

### PR DESCRIPTION
**Pull request by itsmeshibintmz**
easy to track the steps.

### CODE REVIEW

**Comment by liberodark** [comment]
Sorry but have not understand how that work because you have : 
`Flashing is not allowed in Lock State` when you try to flash boot.
Probably is possible to add how to bypass this in the wiki

**Comment by itsmeshibintmz** [comment]
> Sorry but have not understand how that work because you have : `Flashing is not allowed in Lock State` when you try to flash boot. Probably is possible to add how to bypass this in the wiki

sorry to say, but I don't understand what you are implying here?

**Comment by liberodark** [comment]
I think is important to explain how to unlock your phone.
Need to create mi account & run mi_unlock waiting for 7 days & re run mi_unlock  and now you can install custom rom.

**Comment by itsmeshibintmz** [comment]
> I think is important to explain how to unlock your phone. Need to create mi account & run mi_unlock waiting for 7 days & re run mi_unlock and now you can install custom rom.

'll add it too.

**Pull request closed without merging**
